devbot:
    image: nottinghamuniversity/devbot:latest
    environment:
        - HUBOT_SLACK_TOKEN
        - REDIS_URL=redis://redis
    links:
        - redis

redis:
    image: redis:alpine
    entrypoint: redis-server --appendonly yes